/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lilt.connectors.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.lilt.connectors.JSON;

/**
 * OrganizationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-04T05:51:00.272504138Z[Etc/UTC]", comments = "Generator version: 7.6.0-SNAPSHOT")
public class OrganizationResponse {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_INSTANT_TRANSLATION_CREDITS = "instantTranslationCredits";
  @SerializedName(SERIALIZED_NAME_INSTANT_TRANSLATION_CREDITS)
  private BigDecimal instantTranslationCredits;

  public static final String SERIALIZED_NAME_VERIFIED_TRANSLATION_CREDITS = "verifiedTranslationCredits";
  @SerializedName(SERIALIZED_NAME_VERIFIED_TRANSLATION_CREDITS)
  private BigDecimal verifiedTranslationCredits;

  public OrganizationResponse() {
  }

  public OrganizationResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the organization
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public OrganizationResponse instantTranslationCredits(BigDecimal instantTranslationCredits) {
    this.instantTranslationCredits = instantTranslationCredits;
    return this;
  }

   /**
   * The amount of credits the organization has remaining 
   * @return instantTranslationCredits
  **/
  @javax.annotation.Nullable
  public BigDecimal getInstantTranslationCredits() {
    return instantTranslationCredits;
  }

  public void setInstantTranslationCredits(BigDecimal instantTranslationCredits) {
    this.instantTranslationCredits = instantTranslationCredits;
  }


  public OrganizationResponse verifiedTranslationCredits(BigDecimal verifiedTranslationCredits) {
    this.verifiedTranslationCredits = verifiedTranslationCredits;
    return this;
  }

   /**
   * The amount of credits the organization has remaining 
   * @return verifiedTranslationCredits
  **/
  @javax.annotation.Nullable
  public BigDecimal getVerifiedTranslationCredits() {
    return verifiedTranslationCredits;
  }

  public void setVerifiedTranslationCredits(BigDecimal verifiedTranslationCredits) {
    this.verifiedTranslationCredits = verifiedTranslationCredits;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationResponse organizationResponse = (OrganizationResponse) o;
    return Objects.equals(this.name, organizationResponse.name) &&
        Objects.equals(this.instantTranslationCredits, organizationResponse.instantTranslationCredits) &&
        Objects.equals(this.verifiedTranslationCredits, organizationResponse.verifiedTranslationCredits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, instantTranslationCredits, verifiedTranslationCredits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganizationResponse {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    instantTranslationCredits: ").append(toIndentedString(instantTranslationCredits)).append("\n");
    sb.append("    verifiedTranslationCredits: ").append(toIndentedString(verifiedTranslationCredits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("instantTranslationCredits");
    openapiFields.add("verifiedTranslationCredits");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OrganizationResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrganizationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OrganizationResponse is not found in the empty JSON string", OrganizationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrganizationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OrganizationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrganizationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrganizationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrganizationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrganizationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<OrganizationResponse>() {
           @Override
           public void write(JsonWriter out, OrganizationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrganizationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OrganizationResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OrganizationResponse
  * @throws IOException if the JSON string is invalid with respect to OrganizationResponse
  */
  public static OrganizationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrganizationResponse.class);
  }

 /**
  * Convert an instance of OrganizationResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

