/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lilt.connectors.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.lilt.connectors.JSON;

/**
 * SettingsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-04T05:51:00.272504138Z[Etc/UTC]", comments = "Generator version: 7.6.0-SNAPSHOT")
public class SettingsResponse {
  public static final String SERIALIZED_NAME_PROJECT_PREFIX = "project_prefix";
  @SerializedName(SERIALIZED_NAME_PROJECT_PREFIX)
  private String projectPrefix;

  public static final String SERIALIZED_NAME_PROJECT_NAME_TEMPLATE = "project_name_template";
  @SerializedName(SERIALIZED_NAME_PROJECT_NAME_TEMPLATE)
  private String projectNameTemplate;

  /**
   * This indicates the translation workflow being used. UNKNOWN will only be displayed in exceptional cases. 
   */
  @JsonAdapter(LiltTranslationWorkflowEnum.Adapter.class)
  public enum LiltTranslationWorkflowEnum {
    INSTANT("INSTANT"),
    
    VERIFIED("VERIFIED"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    LiltTranslationWorkflowEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LiltTranslationWorkflowEnum fromValue(String value) {
      for (LiltTranslationWorkflowEnum b : LiltTranslationWorkflowEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LiltTranslationWorkflowEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LiltTranslationWorkflowEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LiltTranslationWorkflowEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LiltTranslationWorkflowEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      LiltTranslationWorkflowEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_LILT_TRANSLATION_WORKFLOW = "lilt_translation_workflow";
  @SerializedName(SERIALIZED_NAME_LILT_TRANSLATION_WORKFLOW)
  private LiltTranslationWorkflowEnum liltTranslationWorkflow;

  public SettingsResponse() {
  }

  public SettingsResponse projectPrefix(String projectPrefix) {
    this.projectPrefix = projectPrefix;
    return this;
  }

   /**
   * A string value to include in the Project name.
   * @return projectPrefix
  **/
  @javax.annotation.Nullable
  public String getProjectPrefix() {
    return projectPrefix;
  }

  public void setProjectPrefix(String projectPrefix) {
    this.projectPrefix = projectPrefix;
  }


  public SettingsResponse projectNameTemplate(String projectNameTemplate) {
    this.projectNameTemplate = projectNameTemplate;
    return this;
  }

   /**
   * The template string to use when generating Project names.  The available template options are:  - **today** - Today&#39;s date. Formatted as YYYY-MM-DD. - **trglocale** - The target locale for the given project. - **filename** - The name of the current file being uploaded. - **project_prefix** - The project_prefix value provided in the   configuration. - **project_name** - The project_name value assigned to the file in   the code. - **connector_id** - The Connector ID. - **connector_type** - The Connector Type (e.g. \&quot;xtm\&quot;, \&quot;salesforce\&quot;). 
   * @return projectNameTemplate
  **/
  @javax.annotation.Nullable
  public String getProjectNameTemplate() {
    return projectNameTemplate;
  }

  public void setProjectNameTemplate(String projectNameTemplate) {
    this.projectNameTemplate = projectNameTemplate;
  }


  public SettingsResponse liltTranslationWorkflow(LiltTranslationWorkflowEnum liltTranslationWorkflow) {
    this.liltTranslationWorkflow = liltTranslationWorkflow;
    return this;
  }

   /**
   * This indicates the translation workflow being used. UNKNOWN will only be displayed in exceptional cases. 
   * @return liltTranslationWorkflow
  **/
  @javax.annotation.Nullable
  public LiltTranslationWorkflowEnum getLiltTranslationWorkflow() {
    return liltTranslationWorkflow;
  }

  public void setLiltTranslationWorkflow(LiltTranslationWorkflowEnum liltTranslationWorkflow) {
    this.liltTranslationWorkflow = liltTranslationWorkflow;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SettingsResponse settingsResponse = (SettingsResponse) o;
    return Objects.equals(this.projectPrefix, settingsResponse.projectPrefix) &&
        Objects.equals(this.projectNameTemplate, settingsResponse.projectNameTemplate) &&
        Objects.equals(this.liltTranslationWorkflow, settingsResponse.liltTranslationWorkflow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectPrefix, projectNameTemplate, liltTranslationWorkflow);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettingsResponse {\n");
    sb.append("    projectPrefix: ").append(toIndentedString(projectPrefix)).append("\n");
    sb.append("    projectNameTemplate: ").append(toIndentedString(projectNameTemplate)).append("\n");
    sb.append("    liltTranslationWorkflow: ").append(toIndentedString(liltTranslationWorkflow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("project_prefix");
    openapiFields.add("project_name_template");
    openapiFields.add("lilt_translation_workflow");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SettingsResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SettingsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SettingsResponse is not found in the empty JSON string", SettingsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SettingsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SettingsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("project_prefix") != null && !jsonObj.get("project_prefix").isJsonNull()) && !jsonObj.get("project_prefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `project_prefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("project_prefix").toString()));
      }
      if ((jsonObj.get("project_name_template") != null && !jsonObj.get("project_name_template").isJsonNull()) && !jsonObj.get("project_name_template").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `project_name_template` to be a primitive type in the JSON string but got `%s`", jsonObj.get("project_name_template").toString()));
      }
      if ((jsonObj.get("lilt_translation_workflow") != null && !jsonObj.get("lilt_translation_workflow").isJsonNull()) && !jsonObj.get("lilt_translation_workflow").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lilt_translation_workflow` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lilt_translation_workflow").toString()));
      }
      // validate the optional field `lilt_translation_workflow`
      if (jsonObj.get("lilt_translation_workflow") != null && !jsonObj.get("lilt_translation_workflow").isJsonNull()) {
        LiltTranslationWorkflowEnum.validateJsonElement(jsonObj.get("lilt_translation_workflow"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SettingsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SettingsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SettingsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SettingsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SettingsResponse>() {
           @Override
           public void write(JsonWriter out, SettingsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SettingsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SettingsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SettingsResponse
  * @throws IOException if the JSON string is invalid with respect to SettingsResponse
  */
  public static SettingsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SettingsResponse.class);
  }

 /**
  * Convert an instance of SettingsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

