/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lilt.connectors.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.lilt.connectors.JSON;

/**
 * TranslationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-04T05:51:00.272504138Z[Etc/UTC]", comments = "Generator version: 7.6.0-SNAPSHOT")
public class TranslationResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  /**
   * This value tracks the status of the delivery. 
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    IMPORT_COMPLETE("import_complete"),
    
    IMPORT_FAILED("import_failed"),
    
    EXPORT_COMPLETE("export_complete"),
    
    EXPORT_FAILED("export_failed"),
    
    MT_COMPLETE("mt_complete"),
    
    MT_FAILED("mt_failed"),
    
    PLUGIN_COMPLETE("plugin_complete");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_SRC_LANG = "srcLang";
  @SerializedName(SERIALIZED_NAME_SRC_LANG)
  private String srcLang;

  public static final String SERIALIZED_NAME_SRC_LOCALE = "srcLocale";
  @SerializedName(SERIALIZED_NAME_SRC_LOCALE)
  private String srcLocale;

  public static final String SERIALIZED_NAME_TRG_LANG = "trgLang";
  @SerializedName(SERIALIZED_NAME_TRG_LANG)
  private String trgLang;

  public static final String SERIALIZED_NAME_TRG_LOCALE = "trgLocale";
  @SerializedName(SERIALIZED_NAME_TRG_LOCALE)
  private String trgLocale;

  public static final String SERIALIZED_NAME_ERROR_MSG = "errorMsg";
  @SerializedName(SERIALIZED_NAME_ERROR_MSG)
  private String errorMsg;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public TranslationResponse() {
  }

  public TranslationResponse id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  public TranslationResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public TranslationResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * This value tracks the status of the delivery. 
   * @return status
  **/
  @javax.annotation.Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public TranslationResponse srcLang(String srcLang) {
    this.srcLang = srcLang;
    return this;
  }

   /**
   * Get srcLang
   * @return srcLang
  **/
  @javax.annotation.Nonnull
  public String getSrcLang() {
    return srcLang;
  }

  public void setSrcLang(String srcLang) {
    this.srcLang = srcLang;
  }


  public TranslationResponse srcLocale(String srcLocale) {
    this.srcLocale = srcLocale;
    return this;
  }

   /**
   * Get srcLocale
   * @return srcLocale
  **/
  @javax.annotation.Nullable
  public String getSrcLocale() {
    return srcLocale;
  }

  public void setSrcLocale(String srcLocale) {
    this.srcLocale = srcLocale;
  }


  public TranslationResponse trgLang(String trgLang) {
    this.trgLang = trgLang;
    return this;
  }

   /**
   * Get trgLang
   * @return trgLang
  **/
  @javax.annotation.Nonnull
  public String getTrgLang() {
    return trgLang;
  }

  public void setTrgLang(String trgLang) {
    this.trgLang = trgLang;
  }


  public TranslationResponse trgLocale(String trgLocale) {
    this.trgLocale = trgLocale;
    return this;
  }

   /**
   * Get trgLocale
   * @return trgLocale
  **/
  @javax.annotation.Nullable
  public String getTrgLocale() {
    return trgLocale;
  }

  public void setTrgLocale(String trgLocale) {
    this.trgLocale = trgLocale;
  }


  public TranslationResponse errorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
    return this;
  }

   /**
   * Get errorMsg
   * @return errorMsg
  **/
  @javax.annotation.Nullable
  public String getErrorMsg() {
    return errorMsg;
  }

  public void setErrorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
  }


  public TranslationResponse createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TranslationResponse updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranslationResponse translationResponse = (TranslationResponse) o;
    return Objects.equals(this.id, translationResponse.id) &&
        Objects.equals(this.name, translationResponse.name) &&
        Objects.equals(this.status, translationResponse.status) &&
        Objects.equals(this.srcLang, translationResponse.srcLang) &&
        Objects.equals(this.srcLocale, translationResponse.srcLocale) &&
        Objects.equals(this.trgLang, translationResponse.trgLang) &&
        Objects.equals(this.trgLocale, translationResponse.trgLocale) &&
        Objects.equals(this.errorMsg, translationResponse.errorMsg) &&
        Objects.equals(this.createdAt, translationResponse.createdAt) &&
        Objects.equals(this.updatedAt, translationResponse.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, status, srcLang, srcLocale, trgLang, trgLocale, errorMsg, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranslationResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    srcLang: ").append(toIndentedString(srcLang)).append("\n");
    sb.append("    srcLocale: ").append(toIndentedString(srcLocale)).append("\n");
    sb.append("    trgLang: ").append(toIndentedString(trgLang)).append("\n");
    sb.append("    trgLocale: ").append(toIndentedString(trgLocale)).append("\n");
    sb.append("    errorMsg: ").append(toIndentedString(errorMsg)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("status");
    openapiFields.add("srcLang");
    openapiFields.add("srcLocale");
    openapiFields.add("trgLang");
    openapiFields.add("trgLocale");
    openapiFields.add("errorMsg");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("srcLang");
    openapiRequiredFields.add("trgLang");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("updatedAt");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TranslationResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TranslationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TranslationResponse is not found in the empty JSON string", TranslationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TranslationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TranslationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TranslationResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the required field `status`
      StatusEnum.validateJsonElement(jsonObj.get("status"));
      if (!jsonObj.get("srcLang").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `srcLang` to be a primitive type in the JSON string but got `%s`", jsonObj.get("srcLang").toString()));
      }
      if ((jsonObj.get("srcLocale") != null && !jsonObj.get("srcLocale").isJsonNull()) && !jsonObj.get("srcLocale").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `srcLocale` to be a primitive type in the JSON string but got `%s`", jsonObj.get("srcLocale").toString()));
      }
      if (!jsonObj.get("trgLang").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trgLang` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trgLang").toString()));
      }
      if ((jsonObj.get("trgLocale") != null && !jsonObj.get("trgLocale").isJsonNull()) && !jsonObj.get("trgLocale").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trgLocale` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trgLocale").toString()));
      }
      if ((jsonObj.get("errorMsg") != null && !jsonObj.get("errorMsg").isJsonNull()) && !jsonObj.get("errorMsg").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `errorMsg` to be a primitive type in the JSON string but got `%s`", jsonObj.get("errorMsg").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TranslationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TranslationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TranslationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TranslationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<TranslationResponse>() {
           @Override
           public void write(JsonWriter out, TranslationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TranslationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TranslationResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TranslationResponse
  * @throws IOException if the JSON string is invalid with respect to TranslationResponse
  */
  public static TranslationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TranslationResponse.class);
  }

 /**
  * Convert an instance of TranslationResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

