/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import LiltConnectorSDK.ApiCallback;
import LiltConnectorSDK.ApiClient;
import LiltConnectorSDK.ApiException;
import LiltConnectorSDK.ApiResponse;
import LiltConnectorSDK.Configuration;
import LiltConnectorSDK.Pair;
import LiltConnectorSDK.ProgressRequestBody;
import LiltConnectorSDK.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.OrganizationResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrganizationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OrganizationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OrganizationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for servicesApiOrganizationGetOrganizationRecord
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiOrganizationGetOrganizationRecordCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/organization";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiOrganizationGetOrganizationRecordValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return servicesApiOrganizationGetOrganizationRecordCall(_callback);

    }

    /**
     * Get information about the organization based on lilt_token 
     * 
     * @return OrganizationResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public OrganizationResponse servicesApiOrganizationGetOrganizationRecord() throws ApiException {
        ApiResponse<OrganizationResponse> localVarResp = servicesApiOrganizationGetOrganizationRecordWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get information about the organization based on lilt_token 
     * 
     * @return ApiResponse&lt;OrganizationResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrganizationResponse> servicesApiOrganizationGetOrganizationRecordWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = servicesApiOrganizationGetOrganizationRecordValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<OrganizationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get information about the organization based on lilt_token  (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiOrganizationGetOrganizationRecordAsync(final ApiCallback<OrganizationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiOrganizationGetOrganizationRecordValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<OrganizationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
