/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

/*-
 * #%L
 * com.lilt.connectors.client:lilt-connector-sdk-java
 * %%
 * Copyright (C) 2015 - 2025 Lilt
 * %%
 * Lilt Client Library License – Source Supplied, Permissive, Attribution, Noncommercial
 * 
 * THE LILT CLIENT LIBRARY SOFTWARE OR WORK (AS DEFINED BELOW) IS PROVIDED UNDER
 * THE TERMS OF THIS ("LICENSE"). THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER
 * APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE
 * OR COPYRIGHT LAW IS PROHIBITED. BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED
 * HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE
 * EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU
 * THE RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND
 * CONDITIONS.
 * #L%
 */

import LiltConnectorSDK.ApiCallback;
import LiltConnectorSDK.ApiClient;
import LiltConnectorSDK.ApiException;
import LiltConnectorSDK.ApiResponse;
import LiltConnectorSDK.Configuration;
import LiltConnectorSDK.Pair;
import LiltConnectorSDK.ProgressRequestBody;
import LiltConnectorSDK.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.SettingsResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SettingsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SettingsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SettingsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for servicesApiSettingsGetSettings
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiSettingsGetSettingsCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/settings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiSettingsGetSettingsValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return servicesApiSettingsGetSettingsCall(_callback);

    }

    /**
     * Retrieve the settings.
     * 
     * @return SettingsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public SettingsResponse servicesApiSettingsGetSettings() throws ApiException {
        ApiResponse<SettingsResponse> localVarResp = servicesApiSettingsGetSettingsWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Retrieve the settings.
     * 
     * @return ApiResponse&lt;SettingsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SettingsResponse> servicesApiSettingsGetSettingsWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = servicesApiSettingsGetSettingsValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<SettingsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve the settings. (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiSettingsGetSettingsAsync(final ApiCallback<SettingsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiSettingsGetSettingsValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<SettingsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiSettingsUpdateSettings
     * @param settingsResponse  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiSettingsUpdateSettingsCall(SettingsResponse settingsResponse, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = settingsResponse;

        // create path and map variables
        String localVarPath = "/settings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiSettingsUpdateSettingsValidateBeforeCall(SettingsResponse settingsResponse, final ApiCallback _callback) throws ApiException {
        return servicesApiSettingsUpdateSettingsCall(settingsResponse, _callback);

    }

    /**
     * Update the settings.
     * 
     * @param settingsResponse  (optional)
     * @return SettingsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public SettingsResponse servicesApiSettingsUpdateSettings(SettingsResponse settingsResponse) throws ApiException {
        ApiResponse<SettingsResponse> localVarResp = servicesApiSettingsUpdateSettingsWithHttpInfo(settingsResponse);
        return localVarResp.getData();
    }

    /**
     * Update the settings.
     * 
     * @param settingsResponse  (optional)
     * @return ApiResponse&lt;SettingsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SettingsResponse> servicesApiSettingsUpdateSettingsWithHttpInfo(SettingsResponse settingsResponse) throws ApiException {
        okhttp3.Call localVarCall = servicesApiSettingsUpdateSettingsValidateBeforeCall(settingsResponse, null);
        Type localVarReturnType = new TypeToken<SettingsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update the settings. (asynchronously)
     * 
     * @param settingsResponse  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The settings response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiSettingsUpdateSettingsAsync(SettingsResponse settingsResponse, final ApiCallback<SettingsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiSettingsUpdateSettingsValidateBeforeCall(settingsResponse, _callback);
        Type localVarReturnType = new TypeToken<SettingsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
