/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

/*-
 * #%L
 * com.lilt.connectors.client:lilt-connector-sdk-java
 * %%
 * Copyright (C) 2015 - 2025 Lilt
 * %%
 * Lilt Client Library License – Source Supplied, Permissive, Attribution, Noncommercial
 * 
 * THE LILT CLIENT LIBRARY SOFTWARE OR WORK (AS DEFINED BELOW) IS PROVIDED UNDER
 * THE TERMS OF THIS ("LICENSE"). THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER
 * APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE
 * OR COPYRIGHT LAW IS PROHIBITED. BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED
 * HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE
 * EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU
 * THE RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND
 * CONDITIONS.
 * #L%
 */

import LiltConnectorSDK.ApiCallback;
import LiltConnectorSDK.ApiClient;
import LiltConnectorSDK.ApiException;
import LiltConnectorSDK.ApiResponse;
import LiltConnectorSDK.Configuration;
import LiltConnectorSDK.Pair;
import LiltConnectorSDK.ProgressRequestBody;
import LiltConnectorSDK.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.PreviewTranslationResponseInner;
import org.openapitools.client.model.TranslationResponse;
import org.openapitools.client.model.TranslationsResponse;
import org.openapitools.client.model.UpdateDeliveryOptions;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TranslationsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TranslationsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TranslationsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for servicesApiDeliveriesCompleteDelivery
     * @param id The ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesCompleteDeliveryCall(Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/translations/{id}/complete"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiDeliveriesCompleteDeliveryValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiDeliveriesCompleteDelivery(Async)");
        }

        return servicesApiDeliveriesCompleteDeliveryCall(id, _callback);

    }

    /**
     * Complete a Translation.
     * 
     * @param id The ID. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public void servicesApiDeliveriesCompleteDelivery(Integer id) throws ApiException {
        servicesApiDeliveriesCompleteDeliveryWithHttpInfo(id);
    }

    /**
     * Complete a Translation.
     * 
     * @param id The ID. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> servicesApiDeliveriesCompleteDeliveryWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = servicesApiDeliveriesCompleteDeliveryValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Complete a Translation. (asynchronously)
     * 
     * @param id The ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesCompleteDeliveryAsync(Integer id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiDeliveriesCompleteDeliveryValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiDeliveriesDownloadDelivery
     * @param id The ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation contents. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesDownloadDeliveryCall(Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/translations/{id}/download"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/octet-stream",
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiDeliveriesDownloadDeliveryValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiDeliveriesDownloadDelivery(Async)");
        }

        return servicesApiDeliveriesDownloadDeliveryCall(id, _callback);

    }

    /**
     * Download a Translation.
     * 
     * @param id The ID. (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation contents. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public String servicesApiDeliveriesDownloadDelivery(Integer id) throws ApiException {
        ApiResponse<String> localVarResp = servicesApiDeliveriesDownloadDeliveryWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Download a Translation.
     * 
     * @param id The ID. (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation contents. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> servicesApiDeliveriesDownloadDeliveryWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = servicesApiDeliveriesDownloadDeliveryValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Download a Translation. (asynchronously)
     * 
     * @param id The ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation contents. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesDownloadDeliveryAsync(Integer id, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiDeliveriesDownloadDeliveryValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiDeliveriesDownloadDeliverySource
     * @param id The ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation source contents. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesDownloadDeliverySourceCall(Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/translations/{id}/source"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/octet-stream",
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiDeliveriesDownloadDeliverySourceValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiDeliveriesDownloadDeliverySource(Async)");
        }

        return servicesApiDeliveriesDownloadDeliverySourceCall(id, _callback);

    }

    /**
     * Download a Translation Source.
     * 
     * @param id The ID. (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation source contents. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public String servicesApiDeliveriesDownloadDeliverySource(Integer id) throws ApiException {
        ApiResponse<String> localVarResp = servicesApiDeliveriesDownloadDeliverySourceWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Download a Translation Source.
     * 
     * @param id The ID. (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation source contents. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> servicesApiDeliveriesDownloadDeliverySourceWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = servicesApiDeliveriesDownloadDeliverySourceValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Download a Translation Source. (asynchronously)
     * 
     * @param id The ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation source contents. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesDownloadDeliverySourceAsync(Integer id, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiDeliveriesDownloadDeliverySourceValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiDeliveriesGetDeliveriesByJobId
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param jobId The Job ID. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translations response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesGetDeliveriesByJobIdCall(Integer limit, Integer start, Integer jobId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/translations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (start != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start", start));
        }

        if (jobId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("job_id", jobId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiDeliveriesGetDeliveriesByJobIdValidateBeforeCall(Integer limit, Integer start, Integer jobId, final ApiCallback _callback) throws ApiException {
        return servicesApiDeliveriesGetDeliveriesByJobIdCall(limit, start, jobId, _callback);

    }

    /**
     * Retrieve a list of Translations.
     * 
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param jobId The Job ID. (optional)
     * @return TranslationsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translations response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public TranslationsResponse servicesApiDeliveriesGetDeliveriesByJobId(Integer limit, Integer start, Integer jobId) throws ApiException {
        ApiResponse<TranslationsResponse> localVarResp = servicesApiDeliveriesGetDeliveriesByJobIdWithHttpInfo(limit, start, jobId);
        return localVarResp.getData();
    }

    /**
     * Retrieve a list of Translations.
     * 
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param jobId The Job ID. (optional)
     * @return ApiResponse&lt;TranslationsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translations response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TranslationsResponse> servicesApiDeliveriesGetDeliveriesByJobIdWithHttpInfo(Integer limit, Integer start, Integer jobId) throws ApiException {
        okhttp3.Call localVarCall = servicesApiDeliveriesGetDeliveriesByJobIdValidateBeforeCall(limit, start, jobId, null);
        Type localVarReturnType = new TypeToken<TranslationsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve a list of Translations. (asynchronously)
     * 
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param jobId The Job ID. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translations response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesGetDeliveriesByJobIdAsync(Integer limit, Integer start, Integer jobId, final ApiCallback<TranslationsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiDeliveriesGetDeliveriesByJobIdValidateBeforeCall(limit, start, jobId, _callback);
        Type localVarReturnType = new TypeToken<TranslationsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiDeliveriesGetDeliveryById
     * @param id The ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesGetDeliveryByIdCall(Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/translations/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiDeliveriesGetDeliveryByIdValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiDeliveriesGetDeliveryById(Async)");
        }

        return servicesApiDeliveriesGetDeliveryByIdCall(id, _callback);

    }

    /**
     * Retrieve a Translation.
     * 
     * @param id The ID. (required)
     * @return TranslationResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public TranslationResponse servicesApiDeliveriesGetDeliveryById(Integer id) throws ApiException {
        ApiResponse<TranslationResponse> localVarResp = servicesApiDeliveriesGetDeliveryByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Retrieve a Translation.
     * 
     * @param id The ID. (required)
     * @return ApiResponse&lt;TranslationResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TranslationResponse> servicesApiDeliveriesGetDeliveryByIdWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = servicesApiDeliveriesGetDeliveryByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<TranslationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve a Translation. (asynchronously)
     * 
     * @param id The ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesGetDeliveryByIdAsync(Integer id, final ApiCallback<TranslationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiDeliveriesGetDeliveryByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<TranslationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiDeliveriesPreviewDelivery
     * @param id The ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesPreviewDeliveryCall(Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/translations/{id}/preview"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiDeliveriesPreviewDeliveryValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiDeliveriesPreviewDelivery(Async)");
        }

        return servicesApiDeliveriesPreviewDeliveryCall(id, _callback);

    }

    /**
     * Get a Translation&#39;s source to target mapping.
     * 
     * @param id The ID. (required)
     * @return List&lt;PreviewTranslationResponseInner&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public List<PreviewTranslationResponseInner> servicesApiDeliveriesPreviewDelivery(Integer id) throws ApiException {
        ApiResponse<List<PreviewTranslationResponseInner>> localVarResp = servicesApiDeliveriesPreviewDeliveryWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get a Translation&#39;s source to target mapping.
     * 
     * @param id The ID. (required)
     * @return ApiResponse&lt;List&lt;PreviewTranslationResponseInner&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<PreviewTranslationResponseInner>> servicesApiDeliveriesPreviewDeliveryWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = servicesApiDeliveriesPreviewDeliveryValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<List<PreviewTranslationResponseInner>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a Translation&#39;s source to target mapping. (asynchronously)
     * 
     * @param id The ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesPreviewDeliveryAsync(Integer id, final ApiCallback<List<PreviewTranslationResponseInner>> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiDeliveriesPreviewDeliveryValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<List<PreviewTranslationResponseInner>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiDeliveriesUpdateDelivery
     * @param id The ID. (required)
     * @param updateDeliveryOptions  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesUpdateDeliveryCall(Integer id, UpdateDeliveryOptions updateDeliveryOptions, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateDeliveryOptions;

        // create path and map variables
        String localVarPath = "/translations/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiDeliveriesUpdateDeliveryValidateBeforeCall(Integer id, UpdateDeliveryOptions updateDeliveryOptions, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiDeliveriesUpdateDelivery(Async)");
        }

        return servicesApiDeliveriesUpdateDeliveryCall(id, updateDeliveryOptions, _callback);

    }

    /**
     * Update a Translation.
     * 
     * @param id The ID. (required)
     * @param updateDeliveryOptions  (optional)
     * @return TranslationResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public TranslationResponse servicesApiDeliveriesUpdateDelivery(Integer id, UpdateDeliveryOptions updateDeliveryOptions) throws ApiException {
        ApiResponse<TranslationResponse> localVarResp = servicesApiDeliveriesUpdateDeliveryWithHttpInfo(id, updateDeliveryOptions);
        return localVarResp.getData();
    }

    /**
     * Update a Translation.
     * 
     * @param id The ID. (required)
     * @param updateDeliveryOptions  (optional)
     * @return ApiResponse&lt;TranslationResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TranslationResponse> servicesApiDeliveriesUpdateDeliveryWithHttpInfo(Integer id, UpdateDeliveryOptions updateDeliveryOptions) throws ApiException {
        okhttp3.Call localVarCall = servicesApiDeliveriesUpdateDeliveryValidateBeforeCall(id, updateDeliveryOptions, null);
        Type localVarReturnType = new TypeToken<TranslationResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a Translation. (asynchronously)
     * 
     * @param id The ID. (required)
     * @param updateDeliveryOptions  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The translation response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiDeliveriesUpdateDeliveryAsync(Integer id, UpdateDeliveryOptions updateDeliveryOptions, final ApiCallback<TranslationResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiDeliveriesUpdateDeliveryValidateBeforeCall(id, updateDeliveryOptions, _callback);
        Type localVarReturnType = new TypeToken<TranslationResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
