/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrganizationResponse
 */
public class OrganizationResponseTest {
    private final OrganizationResponse model = new OrganizationResponse();

    /**
     * Model tests for OrganizationResponse
     */
    @Test
    public void testOrganizationResponse() {
        // TODO: test OrganizationResponse
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'instantTranslationCredits'
     */
    @Test
    public void instantTranslationCreditsTest() {
        // TODO: test instantTranslationCredits
    }

    /**
     * Test the property 'verifiedTranslationCredits'
     */
    @Test
    public void verifiedTranslationCreditsTest() {
        // TODO: test verifiedTranslationCredits
    }

}
