/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lilt.connectors.api;

import com.lilt.connectors.ApiCallback;
import com.lilt.connectors.ApiClient;
import com.lilt.connectors.ApiException;
import com.lilt.connectors.ApiResponse;
import com.lilt.connectors.Configuration;
import com.lilt.connectors.Pair;
import com.lilt.connectors.ProgressRequestBody;
import com.lilt.connectors.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.lilt.connectors.model.ErrorResponse;
import java.io.File;
import com.lilt.connectors.model.JobResponse;
import com.lilt.connectors.model.JobsResponse;
import com.lilt.connectors.model.NewJobOptions;
import java.time.OffsetDateTime;
import com.lilt.connectors.model.UpdateJobOptions;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class JobsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public JobsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public JobsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for servicesApiJobsAddFile
     * @param id The Job ID. (required)
     * @param name The file name. (required)
     * @param trglang The target language. Many target languages can be added to a source file. To add more than one target language pass in the trglang query parameter multiple times. For example: ?trglang&#x3D;fr-FR&amp;trglang&#x3D;es-ES.  (required)
     * @param srclang The source language. (optional, default to en-US)
     * @param due The due date for the file as an ISO-8601 string. (optional)
     * @param body  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsAddFileCall(Integer id, String name, List<String> trglang, String srclang, OffsetDateTime due, File body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/jobs/{id}/files"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (name != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("name", name));
        }

        if (srclang != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("srclang", srclang));
        }

        if (trglang != null) {
            localVarCollectionQueryParams.addAll(localVarApiClient.parameterToPairs("multi", "trglang", trglang));
        }

        if (due != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("due", due));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/octet-stream"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiJobsAddFileValidateBeforeCall(Integer id, String name, List<String> trglang, String srclang, OffsetDateTime due, File body, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiJobsAddFile(Async)");
        }

        // verify the required parameter 'name' is set
        if (name == null) {
            throw new ApiException("Missing the required parameter 'name' when calling servicesApiJobsAddFile(Async)");
        }

        // verify the required parameter 'trglang' is set
        if (trglang == null) {
            throw new ApiException("Missing the required parameter 'trglang' when calling servicesApiJobsAddFile(Async)");
        }

        return servicesApiJobsAddFileCall(id, name, trglang, srclang, due, body, _callback);

    }

    /**
     * Add a file to a Job.
     * Add files to a job to submit them for translation. 
     * @param id The Job ID. (required)
     * @param name The file name. (required)
     * @param trglang The target language. Many target languages can be added to a source file. To add more than one target language pass in the trglang query parameter multiple times. For example: ?trglang&#x3D;fr-FR&amp;trglang&#x3D;es-ES.  (required)
     * @param srclang The source language. (optional, default to en-US)
     * @param due The due date for the file as an ISO-8601 string. (optional)
     * @param body  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public void servicesApiJobsAddFile(Integer id, String name, List<String> trglang, String srclang, OffsetDateTime due, File body) throws ApiException {
        servicesApiJobsAddFileWithHttpInfo(id, name, trglang, srclang, due, body);
    }

    /**
     * Add a file to a Job.
     * Add files to a job to submit them for translation. 
     * @param id The Job ID. (required)
     * @param name The file name. (required)
     * @param trglang The target language. Many target languages can be added to a source file. To add more than one target language pass in the trglang query parameter multiple times. For example: ?trglang&#x3D;fr-FR&amp;trglang&#x3D;es-ES.  (required)
     * @param srclang The source language. (optional, default to en-US)
     * @param due The due date for the file as an ISO-8601 string. (optional)
     * @param body  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> servicesApiJobsAddFileWithHttpInfo(Integer id, String name, List<String> trglang, String srclang, OffsetDateTime due, File body) throws ApiException {
        okhttp3.Call localVarCall = servicesApiJobsAddFileValidateBeforeCall(id, name, trglang, srclang, due, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Add a file to a Job. (asynchronously)
     * Add files to a job to submit them for translation. 
     * @param id The Job ID. (required)
     * @param name The file name. (required)
     * @param trglang The target language. Many target languages can be added to a source file. To add more than one target language pass in the trglang query parameter multiple times. For example: ?trglang&#x3D;fr-FR&amp;trglang&#x3D;es-ES.  (required)
     * @param srclang The source language. (optional, default to en-US)
     * @param due The due date for the file as an ISO-8601 string. (optional)
     * @param body  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsAddFileAsync(Integer id, String name, List<String> trglang, String srclang, OffsetDateTime due, File body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiJobsAddFileValidateBeforeCall(id, name, trglang, srclang, due, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiJobsCreateJob
     * @param newJobOptions  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsCreateJobCall(NewJobOptions newJobOptions, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = newJobOptions;

        // create path and map variables
        String localVarPath = "/jobs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiJobsCreateJobValidateBeforeCall(NewJobOptions newJobOptions, final ApiCallback _callback) throws ApiException {
        return servicesApiJobsCreateJobCall(newJobOptions, _callback);

    }

    /**
     * Create a Connector Job.
     * The general workflow for a job is as follows.  1. Create a job. 1. Add files to a job. 1. Start the job. 1. Poll for translation completion. 1. Download the translated files. 
     * @param newJobOptions  (optional)
     * @return JobResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public JobResponse servicesApiJobsCreateJob(NewJobOptions newJobOptions) throws ApiException {
        ApiResponse<JobResponse> localVarResp = servicesApiJobsCreateJobWithHttpInfo(newJobOptions);
        return localVarResp.getData();
    }

    /**
     * Create a Connector Job.
     * The general workflow for a job is as follows.  1. Create a job. 1. Add files to a job. 1. Start the job. 1. Poll for translation completion. 1. Download the translated files. 
     * @param newJobOptions  (optional)
     * @return ApiResponse&lt;JobResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobResponse> servicesApiJobsCreateJobWithHttpInfo(NewJobOptions newJobOptions) throws ApiException {
        okhttp3.Call localVarCall = servicesApiJobsCreateJobValidateBeforeCall(newJobOptions, null);
        Type localVarReturnType = new TypeToken<JobResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a Connector Job. (asynchronously)
     * The general workflow for a job is as follows.  1. Create a job. 1. Add files to a job. 1. Start the job. 1. Poll for translation completion. 1. Download the translated files. 
     * @param newJobOptions  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsCreateJobAsync(NewJobOptions newJobOptions, final ApiCallback<JobResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiJobsCreateJobValidateBeforeCall(newJobOptions, _callback);
        Type localVarReturnType = new TypeToken<JobResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiJobsDeleteJobById
     * @param id The Job ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsDeleteJobByIdCall(Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/jobs/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiJobsDeleteJobByIdValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiJobsDeleteJobById(Async)");
        }

        return servicesApiJobsDeleteJobByIdCall(id, _callback);

    }

    /**
     * Delete a Connector Job.
     * 
     * @param id The Job ID. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public void servicesApiJobsDeleteJobById(Integer id) throws ApiException {
        servicesApiJobsDeleteJobByIdWithHttpInfo(id);
    }

    /**
     * Delete a Connector Job.
     * 
     * @param id The Job ID. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> servicesApiJobsDeleteJobByIdWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = servicesApiJobsDeleteJobByIdValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete a Connector Job. (asynchronously)
     * 
     * @param id The Job ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsDeleteJobByIdAsync(Integer id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiJobsDeleteJobByIdValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiJobsGetJobById
     * @param id The Job ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsGetJobByIdCall(Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/jobs/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiJobsGetJobByIdValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiJobsGetJobById(Async)");
        }

        return servicesApiJobsGetJobByIdCall(id, _callback);

    }

    /**
     * Retrieve a Connector Job.
     * 
     * @param id The Job ID. (required)
     * @return JobResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public JobResponse servicesApiJobsGetJobById(Integer id) throws ApiException {
        ApiResponse<JobResponse> localVarResp = servicesApiJobsGetJobByIdWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Retrieve a Connector Job.
     * 
     * @param id The Job ID. (required)
     * @return ApiResponse&lt;JobResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobResponse> servicesApiJobsGetJobByIdWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = servicesApiJobsGetJobByIdValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<JobResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve a Connector Job. (asynchronously)
     * 
     * @param id The Job ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsGetJobByIdAsync(Integer id, final ApiCallback<JobResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiJobsGetJobByIdValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<JobResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiJobsGetJobTranslations
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param order how to order the returned results (optional, default to asc)
     * @param filterOutCompleted Weather it should filter out completed translations (optional, default to false)
     * @param liltTranslationWorkflow Filter by selected translation workflow (optional)
     * @param orderStatus Filter by list of order level statuses (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The jobs response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsGetJobTranslationsCall(Integer limit, Integer start, String order, Boolean filterOutCompleted, String liltTranslationWorkflow, String orderStatus, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/jobs/translations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (start != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start", start));
        }

        if (order != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("order", order));
        }

        if (filterOutCompleted != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("filter_out_completed", filterOutCompleted));
        }

        if (liltTranslationWorkflow != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("lilt_translation_workflow", liltTranslationWorkflow));
        }

        if (orderStatus != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("order_status", orderStatus));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiJobsGetJobTranslationsValidateBeforeCall(Integer limit, Integer start, String order, Boolean filterOutCompleted, String liltTranslationWorkflow, String orderStatus, final ApiCallback _callback) throws ApiException {
        return servicesApiJobsGetJobTranslationsCall(limit, start, order, filterOutCompleted, liltTranslationWorkflow, orderStatus, _callback);

    }

    /**
     * Retrieve a list of Translations with their Job information.
     * 
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param order how to order the returned results (optional, default to asc)
     * @param filterOutCompleted Weather it should filter out completed translations (optional, default to false)
     * @param liltTranslationWorkflow Filter by selected translation workflow (optional)
     * @param orderStatus Filter by list of order level statuses (optional)
     * @return JobsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The jobs response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public JobsResponse servicesApiJobsGetJobTranslations(Integer limit, Integer start, String order, Boolean filterOutCompleted, String liltTranslationWorkflow, String orderStatus) throws ApiException {
        ApiResponse<JobsResponse> localVarResp = servicesApiJobsGetJobTranslationsWithHttpInfo(limit, start, order, filterOutCompleted, liltTranslationWorkflow, orderStatus);
        return localVarResp.getData();
    }

    /**
     * Retrieve a list of Translations with their Job information.
     * 
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param order how to order the returned results (optional, default to asc)
     * @param filterOutCompleted Weather it should filter out completed translations (optional, default to false)
     * @param liltTranslationWorkflow Filter by selected translation workflow (optional)
     * @param orderStatus Filter by list of order level statuses (optional)
     * @return ApiResponse&lt;JobsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The jobs response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobsResponse> servicesApiJobsGetJobTranslationsWithHttpInfo(Integer limit, Integer start, String order, Boolean filterOutCompleted, String liltTranslationWorkflow, String orderStatus) throws ApiException {
        okhttp3.Call localVarCall = servicesApiJobsGetJobTranslationsValidateBeforeCall(limit, start, order, filterOutCompleted, liltTranslationWorkflow, orderStatus, null);
        Type localVarReturnType = new TypeToken<JobsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve a list of Translations with their Job information. (asynchronously)
     * 
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param order how to order the returned results (optional, default to asc)
     * @param filterOutCompleted Weather it should filter out completed translations (optional, default to false)
     * @param liltTranslationWorkflow Filter by selected translation workflow (optional)
     * @param orderStatus Filter by list of order level statuses (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The jobs response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsGetJobTranslationsAsync(Integer limit, Integer start, String order, Boolean filterOutCompleted, String liltTranslationWorkflow, String orderStatus, final ApiCallback<JobsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiJobsGetJobTranslationsValidateBeforeCall(limit, start, order, filterOutCompleted, liltTranslationWorkflow, orderStatus, _callback);
        Type localVarReturnType = new TypeToken<JobsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiJobsGetJobs
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param order how to order the returned results (optional, default to asc)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The jobs response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsGetJobsCall(Integer limit, Integer start, String order, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/jobs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (start != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start", start));
        }

        if (order != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("order", order));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiJobsGetJobsValidateBeforeCall(Integer limit, Integer start, String order, final ApiCallback _callback) throws ApiException {
        return servicesApiJobsGetJobsCall(limit, start, order, _callback);

    }

    /**
     * Retrieve a list of Connector Jobs.
     * 
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param order how to order the returned results (optional, default to asc)
     * @return JobsResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The jobs response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public JobsResponse servicesApiJobsGetJobs(Integer limit, Integer start, String order) throws ApiException {
        ApiResponse<JobsResponse> localVarResp = servicesApiJobsGetJobsWithHttpInfo(limit, start, order);
        return localVarResp.getData();
    }

    /**
     * Retrieve a list of Connector Jobs.
     * 
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param order how to order the returned results (optional, default to asc)
     * @return ApiResponse&lt;JobsResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The jobs response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobsResponse> servicesApiJobsGetJobsWithHttpInfo(Integer limit, Integer start, String order) throws ApiException {
        okhttp3.Call localVarCall = servicesApiJobsGetJobsValidateBeforeCall(limit, start, order, null);
        Type localVarReturnType = new TypeToken<JobsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve a list of Connector Jobs. (asynchronously)
     * 
     * @param limit the query limit (optional, default to 25)
     * @param start where to start (optional, default to 0)
     * @param order how to order the returned results (optional, default to asc)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The jobs response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsGetJobsAsync(Integer limit, Integer start, String order, final ApiCallback<JobsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiJobsGetJobsValidateBeforeCall(limit, start, order, _callback);
        Type localVarReturnType = new TypeToken<JobsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiJobsStartJob
     * @param id The Job ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned. Use the job ID to poll for subsequent status changes.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsStartJobCall(Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/jobs/{id}/start"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiJobsStartJobValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiJobsStartJob(Async)");
        }

        return servicesApiJobsStartJobCall(id, _callback);

    }

    /**
     * Start a Job.
     * Start a job once all of the source files have been added. Use the Job ID to poll for completion to ensure everything has been well received by Lilt. 
     * @param id The Job ID. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned. Use the job ID to poll for subsequent status changes.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public void servicesApiJobsStartJob(Integer id) throws ApiException {
        servicesApiJobsStartJobWithHttpInfo(id);
    }

    /**
     * Start a Job.
     * Start a job once all of the source files have been added. Use the Job ID to poll for completion to ensure everything has been well received by Lilt. 
     * @param id The Job ID. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned. Use the job ID to poll for subsequent status changes.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> servicesApiJobsStartJobWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = servicesApiJobsStartJobValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Start a Job. (asynchronously)
     * Start a job once all of the source files have been added. Use the Job ID to poll for completion to ensure everything has been well received by Lilt. 
     * @param id The Job ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned. Use the job ID to poll for subsequent status changes.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsStartJobAsync(Integer id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiJobsStartJobValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiJobsSyncJob
     * @param id The Job ID. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned. Use the job ID to poll for subsequent status changes.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsSyncJobCall(Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/jobs/{id}/sync"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiJobsSyncJobValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiJobsSyncJob(Async)");
        }

        return servicesApiJobsSyncJobCall(id, _callback);

    }

    /**
     * Start a Sync.
     * Checks for updates to the translations. Use the Job ID to poll for successful completion of the sync. When the sync is complete the translations endpoint can be used to view the translation status for the job. 
     * @param id The Job ID. (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned. Use the job ID to poll for subsequent status changes.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public void servicesApiJobsSyncJob(Integer id) throws ApiException {
        servicesApiJobsSyncJobWithHttpInfo(id);
    }

    /**
     * Start a Sync.
     * Checks for updates to the translations. Use the Job ID to poll for successful completion of the sync. When the sync is complete the translations endpoint can be used to view the translation status for the job. 
     * @param id The Job ID. (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned. Use the job ID to poll for subsequent status changes.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> servicesApiJobsSyncJobWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = servicesApiJobsSyncJobValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Start a Sync. (asynchronously)
     * Checks for updates to the translations. Use the Job ID to poll for successful completion of the sync. When the sync is complete the translations endpoint can be used to view the translation status for the job. 
     * @param id The Job ID. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Upon success a response with an empty body is returned. Use the job ID to poll for subsequent status changes.  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The Not Found response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsSyncJobAsync(Integer id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiJobsSyncJobValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for servicesApiJobsUpdateJob
     * @param id The Job ID. (required)
     * @param updateJobOptions  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsUpdateJobCall(Integer id, UpdateJobOptions updateJobOptions, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateJobOptions;

        // create path and map variables
        String localVarPath = "/jobs/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call servicesApiJobsUpdateJobValidateBeforeCall(Integer id, UpdateJobOptions updateJobOptions, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling servicesApiJobsUpdateJob(Async)");
        }

        return servicesApiJobsUpdateJobCall(id, updateJobOptions, _callback);

    }

    /**
     * Update a Connector Job.
     * Update a job to change the status or error message. 
     * @param id The Job ID. (required)
     * @param updateJobOptions  (optional)
     * @return JobResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public JobResponse servicesApiJobsUpdateJob(Integer id, UpdateJobOptions updateJobOptions) throws ApiException {
        ApiResponse<JobResponse> localVarResp = servicesApiJobsUpdateJobWithHttpInfo(id, updateJobOptions);
        return localVarResp.getData();
    }

    /**
     * Update a Connector Job.
     * Update a job to change the status or error message. 
     * @param id The Job ID. (required)
     * @param updateJobOptions  (optional)
     * @return ApiResponse&lt;JobResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<JobResponse> servicesApiJobsUpdateJobWithHttpInfo(Integer id, UpdateJobOptions updateJobOptions) throws ApiException {
        okhttp3.Call localVarCall = servicesApiJobsUpdateJobValidateBeforeCall(id, updateJobOptions, null);
        Type localVarReturnType = new TypeToken<JobResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a Connector Job. (asynchronously)
     * Update a job to change the status or error message. 
     * @param id The Job ID. (required)
     * @param updateJobOptions  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The job response. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> The Bad Request response. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The Unauthorized response. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> The Forbidden response. </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> The Server Error response. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call servicesApiJobsUpdateJobAsync(Integer id, UpdateJobOptions updateJobOptions, final ApiCallback<JobResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = servicesApiJobsUpdateJobValidateBeforeCall(id, updateJobOptions, _callback);
        Type localVarReturnType = new TypeToken<JobResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
