/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

/*-
 * #%L
 * com.lilt.connectors.client:lilt-connector-sdk-java
 * %%
 * Copyright (C) 2015 - 2025 Lilt
 * %%
 * Lilt Client Library License – Source Supplied, Permissive, Attribution, Noncommercial
 * 
 * THE LILT CLIENT LIBRARY SOFTWARE OR WORK (AS DEFINED BELOW) IS PROVIDED UNDER
 * THE TERMS OF THIS ("LICENSE"). THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER
 * APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE
 * OR COPYRIGHT LAW IS PROHIBITED. BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED
 * HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE
 * EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU
 * THE RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND
 * CONDITIONS.
 * #L%
 */

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import LiltConnectorSDK.JSON;

/**
 * NewJobOptions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-05T09:10:14.232589379Z[Etc/UTC]", comments = "Generator version: 7.6.0-SNAPSHOT")
public class NewJobOptions {
  public static final String SERIALIZED_NAME_PROJECT_PREFIX = "project_prefix";
  @SerializedName(SERIALIZED_NAME_PROJECT_PREFIX)
  private String projectPrefix;

  public static final String SERIALIZED_NAME_PROJECT_NAME_TEMPLATE = "project_name_template";
  @SerializedName(SERIALIZED_NAME_PROJECT_NAME_TEMPLATE)
  private String projectNameTemplate;

  /**
   * Gets or Sets liltTranslationWorkflow
   */
  @JsonAdapter(LiltTranslationWorkflowEnum.Adapter.class)
  public enum LiltTranslationWorkflowEnum {
    INSTANT("INSTANT"),
    
    VERIFIED("VERIFIED");

    private String value;

    LiltTranslationWorkflowEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LiltTranslationWorkflowEnum fromValue(String value) {
      for (LiltTranslationWorkflowEnum b : LiltTranslationWorkflowEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LiltTranslationWorkflowEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LiltTranslationWorkflowEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LiltTranslationWorkflowEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LiltTranslationWorkflowEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      LiltTranslationWorkflowEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_LILT_TRANSLATION_WORKFLOW = "lilt_translation_workflow";
  @SerializedName(SERIALIZED_NAME_LILT_TRANSLATION_WORKFLOW)
  private LiltTranslationWorkflowEnum liltTranslationWorkflow;

  public static final String SERIALIZED_NAME_LILT_DEFAULT_DUE_DATE = "lilt_default_due_date";
  @SerializedName(SERIALIZED_NAME_LILT_DEFAULT_DUE_DATE)
  private String liltDefaultDueDate;

  public static final String SERIALIZED_NAME_LILT_TARGET_LANGUAGES = "lilt_target_languages";
  @SerializedName(SERIALIZED_NAME_LILT_TARGET_LANGUAGES)
  private List<String> liltTargetLanguages = new ArrayList<>();

  public static final String SERIALIZED_NAME_HANDLE_CREDIT_TRANSACTIONS = "handle_credit_transactions";
  @SerializedName(SERIALIZED_NAME_HANDLE_CREDIT_TRANSACTIONS)
  private Boolean handleCreditTransactions = false;

  public static final String SERIALIZED_NAME_SOURCE_WORD_COUNT = "source_word_count";
  @SerializedName(SERIALIZED_NAME_SOURCE_WORD_COUNT)
  private BigDecimal sourceWordCount;

  public NewJobOptions() {
  }

  public NewJobOptions projectPrefix(String projectPrefix) {
    this.projectPrefix = projectPrefix;
    return this;
  }

   /**
   * A string value to include in the Project name.
   * @return projectPrefix
  **/
  @javax.annotation.Nullable
  public String getProjectPrefix() {
    return projectPrefix;
  }

  public void setProjectPrefix(String projectPrefix) {
    this.projectPrefix = projectPrefix;
  }


  public NewJobOptions projectNameTemplate(String projectNameTemplate) {
    this.projectNameTemplate = projectNameTemplate;
    return this;
  }

   /**
   * The template string to use when generating Project names.  The available template options are:  - **today** - Today&#39;s date. Formatted as YYYY-MM-DD. - **trglocale** - The target locale for the given project. - **filename** - The name of the current file being uploaded. - **project_prefix** - The project_prefix value provided in the   configuration. - **project_name** - The project_name value assigned to the file in   the code. - **connector_id** - The Connector ID. - **connector_type** - The Connector Type (e.g. \&quot;xtm\&quot;, \&quot;salesforce\&quot;). 
   * @return projectNameTemplate
  **/
  @javax.annotation.Nullable
  public String getProjectNameTemplate() {
    return projectNameTemplate;
  }

  public void setProjectNameTemplate(String projectNameTemplate) {
    this.projectNameTemplate = projectNameTemplate;
  }


  public NewJobOptions liltTranslationWorkflow(LiltTranslationWorkflowEnum liltTranslationWorkflow) {
    this.liltTranslationWorkflow = liltTranslationWorkflow;
    return this;
  }

   /**
   * Get liltTranslationWorkflow
   * @return liltTranslationWorkflow
  **/
  @javax.annotation.Nullable
  public LiltTranslationWorkflowEnum getLiltTranslationWorkflow() {
    return liltTranslationWorkflow;
  }

  public void setLiltTranslationWorkflow(LiltTranslationWorkflowEnum liltTranslationWorkflow) {
    this.liltTranslationWorkflow = liltTranslationWorkflow;
  }


  public NewJobOptions liltDefaultDueDate(String liltDefaultDueDate) {
    this.liltDefaultDueDate = liltDefaultDueDate;
    return this;
  }

   /**
   * The due date to use when creating Lilt Jobs/Projects if no specific due date is specified on the file level. 
   * @return liltDefaultDueDate
  **/
  @javax.annotation.Nullable
  public String getLiltDefaultDueDate() {
    return liltDefaultDueDate;
  }

  public void setLiltDefaultDueDate(String liltDefaultDueDate) {
    this.liltDefaultDueDate = liltDefaultDueDate;
  }


  public NewJobOptions liltTargetLanguages(List<String> liltTargetLanguages) {
    this.liltTargetLanguages = liltTargetLanguages;
    return this;
  }

  public NewJobOptions addLiltTargetLanguagesItem(String liltTargetLanguagesItem) {
    if (this.liltTargetLanguages == null) {
      this.liltTargetLanguages = new ArrayList<>();
    }
    this.liltTargetLanguages.add(liltTargetLanguagesItem);
    return this;
  }

   /**
   * The list of target languages to use for the new job. The values provided should be present in the target_memories section of the configuration. 
   * @return liltTargetLanguages
  **/
  @javax.annotation.Nullable
  public List<String> getLiltTargetLanguages() {
    return liltTargetLanguages;
  }

  public void setLiltTargetLanguages(List<String> liltTargetLanguages) {
    this.liltTargetLanguages = liltTargetLanguages;
  }


  public NewJobOptions handleCreditTransactions(Boolean handleCreditTransactions) {
    this.handleCreditTransactions = handleCreditTransactions;
    return this;
  }

   /**
   * If true, credit transactions will be handled by the connector. If false, no credit transactions will be created for the job. 
   * @return handleCreditTransactions
  **/
  @javax.annotation.Nullable
  public Boolean getHandleCreditTransactions() {
    return handleCreditTransactions;
  }

  public void setHandleCreditTransactions(Boolean handleCreditTransactions) {
    this.handleCreditTransactions = handleCreditTransactions;
  }


  public NewJobOptions sourceWordCount(BigDecimal sourceWordCount) {
    this.sourceWordCount = sourceWordCount;
    return this;
  }

   /**
   * The source word count to use when creating credits transaction for instant transaltion jobs. 
   * @return sourceWordCount
  **/
  @javax.annotation.Nullable
  public BigDecimal getSourceWordCount() {
    return sourceWordCount;
  }

  public void setSourceWordCount(BigDecimal sourceWordCount) {
    this.sourceWordCount = sourceWordCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewJobOptions newJobOptions = (NewJobOptions) o;
    return Objects.equals(this.projectPrefix, newJobOptions.projectPrefix) &&
        Objects.equals(this.projectNameTemplate, newJobOptions.projectNameTemplate) &&
        Objects.equals(this.liltTranslationWorkflow, newJobOptions.liltTranslationWorkflow) &&
        Objects.equals(this.liltDefaultDueDate, newJobOptions.liltDefaultDueDate) &&
        Objects.equals(this.liltTargetLanguages, newJobOptions.liltTargetLanguages) &&
        Objects.equals(this.handleCreditTransactions, newJobOptions.handleCreditTransactions) &&
        Objects.equals(this.sourceWordCount, newJobOptions.sourceWordCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectPrefix, projectNameTemplate, liltTranslationWorkflow, liltDefaultDueDate, liltTargetLanguages, handleCreditTransactions, sourceWordCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewJobOptions {\n");
    sb.append("    projectPrefix: ").append(toIndentedString(projectPrefix)).append("\n");
    sb.append("    projectNameTemplate: ").append(toIndentedString(projectNameTemplate)).append("\n");
    sb.append("    liltTranslationWorkflow: ").append(toIndentedString(liltTranslationWorkflow)).append("\n");
    sb.append("    liltDefaultDueDate: ").append(toIndentedString(liltDefaultDueDate)).append("\n");
    sb.append("    liltTargetLanguages: ").append(toIndentedString(liltTargetLanguages)).append("\n");
    sb.append("    handleCreditTransactions: ").append(toIndentedString(handleCreditTransactions)).append("\n");
    sb.append("    sourceWordCount: ").append(toIndentedString(sourceWordCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("project_prefix");
    openapiFields.add("project_name_template");
    openapiFields.add("lilt_translation_workflow");
    openapiFields.add("lilt_default_due_date");
    openapiFields.add("lilt_target_languages");
    openapiFields.add("handle_credit_transactions");
    openapiFields.add("source_word_count");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to NewJobOptions
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NewJobOptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NewJobOptions is not found in the empty JSON string", NewJobOptions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NewJobOptions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NewJobOptions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("project_prefix") != null && !jsonObj.get("project_prefix").isJsonNull()) && !jsonObj.get("project_prefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `project_prefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("project_prefix").toString()));
      }
      if ((jsonObj.get("project_name_template") != null && !jsonObj.get("project_name_template").isJsonNull()) && !jsonObj.get("project_name_template").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `project_name_template` to be a primitive type in the JSON string but got `%s`", jsonObj.get("project_name_template").toString()));
      }
      if ((jsonObj.get("lilt_translation_workflow") != null && !jsonObj.get("lilt_translation_workflow").isJsonNull()) && !jsonObj.get("lilt_translation_workflow").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lilt_translation_workflow` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lilt_translation_workflow").toString()));
      }
      // validate the optional field `lilt_translation_workflow`
      if (jsonObj.get("lilt_translation_workflow") != null && !jsonObj.get("lilt_translation_workflow").isJsonNull()) {
        LiltTranslationWorkflowEnum.validateJsonElement(jsonObj.get("lilt_translation_workflow"));
      }
      if ((jsonObj.get("lilt_default_due_date") != null && !jsonObj.get("lilt_default_due_date").isJsonNull()) && !jsonObj.get("lilt_default_due_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lilt_default_due_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lilt_default_due_date").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("lilt_target_languages") != null && !jsonObj.get("lilt_target_languages").isJsonNull() && !jsonObj.get("lilt_target_languages").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lilt_target_languages` to be an array in the JSON string but got `%s`", jsonObj.get("lilt_target_languages").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NewJobOptions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NewJobOptions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NewJobOptions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NewJobOptions.class));

       return (TypeAdapter<T>) new TypeAdapter<NewJobOptions>() {
           @Override
           public void write(JsonWriter out, NewJobOptions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NewJobOptions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of NewJobOptions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of NewJobOptions
  * @throws IOException if the JSON string is invalid with respect to NewJobOptions
  */
  public static NewJobOptions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NewJobOptions.class);
  }

 /**
  * Convert an instance of NewJobOptions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

