/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

/*-
 * #%L
 * com.lilt.connectors.client:lilt-connector-sdk-java
 * %%
 * Copyright (C) 2015 - 2025 Lilt
 * %%
 * Lilt Client Library License – Source Supplied, Permissive, Attribution, Noncommercial
 * 
 * THE LILT CLIENT LIBRARY SOFTWARE OR WORK (AS DEFINED BELOW) IS PROVIDED UNDER
 * THE TERMS OF THIS ("LICENSE"). THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER
 * APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE
 * OR COPYRIGHT LAW IS PROHIBITED. BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED
 * HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE
 * EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU
 * THE RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND
 * CONDITIONS.
 * #L%
 */

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import LiltConnectorSDK.JSON;

/**
 * NewOrganizationOptions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-05T09:10:14.232589379Z[Etc/UTC]", comments = "Generator version: 7.6.0-SNAPSHOT")
public class NewOrganizationOptions {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_REGISTRATION_METADATA = "registrationMetadata";
  @SerializedName(SERIALIZED_NAME_REGISTRATION_METADATA)
  private Object registrationMetadata;

  public static final String SERIALIZED_NAME_INSTANT_TRANSLATION_CREDITS = "instantTranslationCredits";
  @SerializedName(SERIALIZED_NAME_INSTANT_TRANSLATION_CREDITS)
  private Integer instantTranslationCredits;

  public static final String SERIALIZED_NAME_VERIFIED_TRANSLATION_CREDITS = "verifiedTranslationCredits";
  @SerializedName(SERIALIZED_NAME_VERIFIED_TRANSLATION_CREDITS)
  private Integer verifiedTranslationCredits;

  public NewOrganizationOptions() {
  }

  public NewOrganizationOptions name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name to identify the organization by
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public NewOrganizationOptions email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Contact email for the owner of the organization
   * @return email
  **/
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  public NewOrganizationOptions registrationMetadata(Object registrationMetadata) {
    this.registrationMetadata = registrationMetadata;
    return this;
  }

   /**
   * Relevant information for the organization being created 
   * @return registrationMetadata
  **/
  @javax.annotation.Nullable
  public Object getRegistrationMetadata() {
    return registrationMetadata;
  }

  public void setRegistrationMetadata(Object registrationMetadata) {
    this.registrationMetadata = registrationMetadata;
  }


  public NewOrganizationOptions instantTranslationCredits(Integer instantTranslationCredits) {
    this.instantTranslationCredits = instantTranslationCredits;
    return this;
  }

   /**
   * Amount of credits the organization starts with, usable for instant translation jobs 
   * @return instantTranslationCredits
  **/
  @javax.annotation.Nullable
  public Integer getInstantTranslationCredits() {
    return instantTranslationCredits;
  }

  public void setInstantTranslationCredits(Integer instantTranslationCredits) {
    this.instantTranslationCredits = instantTranslationCredits;
  }


  public NewOrganizationOptions verifiedTranslationCredits(Integer verifiedTranslationCredits) {
    this.verifiedTranslationCredits = verifiedTranslationCredits;
    return this;
  }

   /**
   * Amount of credits the organization starts with, usable for verified translation jobs 
   * @return verifiedTranslationCredits
  **/
  @javax.annotation.Nullable
  public Integer getVerifiedTranslationCredits() {
    return verifiedTranslationCredits;
  }

  public void setVerifiedTranslationCredits(Integer verifiedTranslationCredits) {
    this.verifiedTranslationCredits = verifiedTranslationCredits;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewOrganizationOptions newOrganizationOptions = (NewOrganizationOptions) o;
    return Objects.equals(this.name, newOrganizationOptions.name) &&
        Objects.equals(this.email, newOrganizationOptions.email) &&
        Objects.equals(this.registrationMetadata, newOrganizationOptions.registrationMetadata) &&
        Objects.equals(this.instantTranslationCredits, newOrganizationOptions.instantTranslationCredits) &&
        Objects.equals(this.verifiedTranslationCredits, newOrganizationOptions.verifiedTranslationCredits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, email, registrationMetadata, instantTranslationCredits, verifiedTranslationCredits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewOrganizationOptions {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    registrationMetadata: ").append(toIndentedString(registrationMetadata)).append("\n");
    sb.append("    instantTranslationCredits: ").append(toIndentedString(instantTranslationCredits)).append("\n");
    sb.append("    verifiedTranslationCredits: ").append(toIndentedString(verifiedTranslationCredits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("email");
    openapiFields.add("registrationMetadata");
    openapiFields.add("instantTranslationCredits");
    openapiFields.add("verifiedTranslationCredits");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to NewOrganizationOptions
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NewOrganizationOptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NewOrganizationOptions is not found in the empty JSON string", NewOrganizationOptions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NewOrganizationOptions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NewOrganizationOptions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NewOrganizationOptions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NewOrganizationOptions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NewOrganizationOptions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NewOrganizationOptions.class));

       return (TypeAdapter<T>) new TypeAdapter<NewOrganizationOptions>() {
           @Override
           public void write(JsonWriter out, NewOrganizationOptions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NewOrganizationOptions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of NewOrganizationOptions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of NewOrganizationOptions
  * @throws IOException if the JSON string is invalid with respect to NewOrganizationOptions
  */
  public static NewOrganizationOptions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NewOrganizationOptions.class);
  }

 /**
  * Convert an instance of NewOrganizationOptions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

