/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

/*-
 * #%L
 * com.lilt.connectors.client:lilt-connector-sdk-java
 * %%
 * Copyright (C) 2015 - 2025 Lilt
 * %%
 * Lilt Client Library License – Source Supplied, Permissive, Attribution, Noncommercial
 * 
 * THE LILT CLIENT LIBRARY SOFTWARE OR WORK (AS DEFINED BELOW) IS PROVIDED UNDER
 * THE TERMS OF THIS ("LICENSE"). THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER
 * APPLICABLE LAW. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE
 * OR COPYRIGHT LAW IS PROHIBITED. BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED
 * HERE, YOU ACCEPT AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. TO THE
 * EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, THE LICENSOR GRANTS YOU
 * THE RIGHTS CONTAINED HERE IN CONSIDERATION OF YOUR ACCEPTANCE OF SUCH TERMS AND
 * CONDITIONS.
 * #L%
 */

import LiltConnectorSDK.ApiException;
import org.openapitools.client.model.ErrorResponse;
import java.io.File;
import org.openapitools.client.model.JobResponse;
import org.openapitools.client.model.JobsResponse;
import org.openapitools.client.model.NewJobOptions;
import java.time.OffsetDateTime;
import org.openapitools.client.model.UpdateJobOptions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for JobsApi
 */
@Disabled
public class JobsApiTest {

    private final JobsApi api = new JobsApi();

    /**
     * Add a file to a Job.
     *
     * Add files to a job to submit them for translation. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiJobsAddFileTest() throws ApiException {
        Integer id = null;
        String name = null;
        List<String> trglang = null;
        String srclang = null;
        OffsetDateTime due = null;
        File body = null;
        api.servicesApiJobsAddFile(id, name, trglang, srclang, due, body);
        // TODO: test validations
    }

    /**
     * Create a Connector Job.
     *
     * The general workflow for a job is as follows.  1. Create a job. 1. Add files to a job. 1. Start the job. 1. Poll for translation completion. 1. Download the translated files. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiJobsCreateJobTest() throws ApiException {
        NewJobOptions newJobOptions = null;
        JobResponse response = api.servicesApiJobsCreateJob(newJobOptions);
        // TODO: test validations
    }

    /**
     * Delete a Connector Job.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiJobsDeleteJobByIdTest() throws ApiException {
        Integer id = null;
        api.servicesApiJobsDeleteJobById(id);
        // TODO: test validations
    }

    /**
     * Retrieve a Connector Job.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiJobsGetJobByIdTest() throws ApiException {
        Integer id = null;
        JobResponse response = api.servicesApiJobsGetJobById(id);
        // TODO: test validations
    }

    /**
     * Retrieve a list of Translations with their Job information.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiJobsGetJobTranslationsTest() throws ApiException {
        Integer limit = null;
        Integer start = null;
        String order = null;
        Boolean filterOutCompleted = null;
        String liltTranslationWorkflow = null;
        String orderStatus = null;
        JobsResponse response = api.servicesApiJobsGetJobTranslations(limit, start, order, filterOutCompleted, liltTranslationWorkflow, orderStatus);
        // TODO: test validations
    }

    /**
     * Retrieve a list of Connector Jobs.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiJobsGetJobsTest() throws ApiException {
        Integer limit = null;
        Integer start = null;
        String order = null;
        JobsResponse response = api.servicesApiJobsGetJobs(limit, start, order);
        // TODO: test validations
    }

    /**
     * Start a Job.
     *
     * Start a job once all of the source files have been added. Use the Job ID to poll for completion to ensure everything has been well received by Lilt. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiJobsStartJobTest() throws ApiException {
        Integer id = null;
        api.servicesApiJobsStartJob(id);
        // TODO: test validations
    }

    /**
     * Start a Sync.
     *
     * Checks for updates to the translations. Use the Job ID to poll for successful completion of the sync. When the sync is complete the translations endpoint can be used to view the translation status for the job. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiJobsSyncJobTest() throws ApiException {
        Integer id = null;
        api.servicesApiJobsSyncJob(id);
        // TODO: test validations
    }

    /**
     * Update a Connector Job.
     *
     * Update a job to change the status or error message. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiJobsUpdateJobTest() throws ApiException {
        Integer id = null;
        UpdateJobOptions updateJobOptions = null;
        JobResponse response = api.servicesApiJobsUpdateJob(id, updateJobOptions);
        // TODO: test validations
    }

}
