/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import LiltConnectorSDK.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.NewOrganizationOptions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RegistrationApi
 */
@Disabled
public class RegistrationApiTest {

    private final RegistrationApi api = new RegistrationApi();

    /**
     * Register a new Connectors Organization
     *
     * This endpoint is used to register a connector organization in preparation to handle credits management. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiRegistrationRegisterCreditsBasedOrganizationTest() throws ApiException {
        NewOrganizationOptions newOrganizationOptions = null;
        api.servicesApiRegistrationRegisterCreditsBasedOrganization(newOrganizationOptions);
        // TODO: test validations
    }

}
