/*
 * Lilt Connector Plugin API
 * This document describes the Plugin API for Lilt's Connector platform. The Plugin API is intented to be used by developers who wish to build integrations into their desired systems. The purpose of this API is to enable content transfer and status monitoring for localization projects.  - Read more about the concepts and workflows in the   [user guide](/docs/api/v1.0). - Test the API interactively via [Swagger UI](/api/v1.0/ui). 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import LiltConnectorSDK.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.PreviewTranslationResponseInner;
import org.openapitools.client.model.TranslationResponse;
import org.openapitools.client.model.TranslationsResponse;
import org.openapitools.client.model.UpdateDeliveryOptions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TranslationsApi
 */
@Disabled
public class TranslationsApiTest {

    private final TranslationsApi api = new TranslationsApi();

    /**
     * Complete a Translation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiDeliveriesCompleteDeliveryTest() throws ApiException {
        Integer id = null;
        api.servicesApiDeliveriesCompleteDelivery(id);
        // TODO: test validations
    }

    /**
     * Download a Translation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiDeliveriesDownloadDeliveryTest() throws ApiException {
        Integer id = null;
        String response = api.servicesApiDeliveriesDownloadDelivery(id);
        // TODO: test validations
    }

    /**
     * Download a Translation Source.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiDeliveriesDownloadDeliverySourceTest() throws ApiException {
        Integer id = null;
        String response = api.servicesApiDeliveriesDownloadDeliverySource(id);
        // TODO: test validations
    }

    /**
     * Retrieve a list of Translations.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiDeliveriesGetDeliveriesByJobIdTest() throws ApiException {
        Integer limit = null;
        Integer start = null;
        Integer jobId = null;
        TranslationsResponse response = api.servicesApiDeliveriesGetDeliveriesByJobId(limit, start, jobId);
        // TODO: test validations
    }

    /**
     * Retrieve a Translation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiDeliveriesGetDeliveryByIdTest() throws ApiException {
        Integer id = null;
        TranslationResponse response = api.servicesApiDeliveriesGetDeliveryById(id);
        // TODO: test validations
    }

    /**
     * Get a Translation&#39;s source to target mapping.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiDeliveriesPreviewDeliveryTest() throws ApiException {
        Integer id = null;
        List<PreviewTranslationResponseInner> response = api.servicesApiDeliveriesPreviewDelivery(id);
        // TODO: test validations
    }

    /**
     * Update a Translation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void servicesApiDeliveriesUpdateDeliveryTest() throws ApiException {
        Integer id = null;
        UpdateDeliveryOptions updateDeliveryOptions = null;
        TranslationResponse response = api.servicesApiDeliveriesUpdateDelivery(id, updateDeliveryOptions);
        // TODO: test validations
    }

}
